name: luhux 博客
url: http://luhux.github.io
description: 一个不善于使用git和写作的用户的博客

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
