theme: jekyll-theme-midnight

# Site settings
#
title: LUHUX
SEOTitle: LUHUX | Blog
header-img: img/home-bg-hill.jpg
# email: @gmail.com
keyword: "LUHUX"
url: "https://luhux.github.io"
# baseurl: ""
# ...
